# -*- coding: utf-8 -*-
"""abc

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dPEOI7F1xyUQkptsPPyAcTNt4ivxrkAF
"""

import multiprocessing

def printsec(seconds):
    from datetime import datetime
    from time import sleep
    sleep(seconds)
    print('wait', seconds, 'seconds, time is', datetime.utcnow())
    
if __name__ == '__main__':
    import random    
    for n in range(3):
        seconds = random.random()
        proc = multiprocessing.Process(target=printsec, args=(seconds,))
        proc.start()

