# -*- coding: utf-8 -*-
"""zoo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J94Wt3ZS4SnTEtlq0MvbGQEILnojAHBe
"""

def hours():
  print("Open 9-5 daily")

